<?php
 /** @var $block \Magento\Catalog\Block\Product\View */
 ?>
 <?php $_product = $block->getProduct(); ?>
 <?php $buttonTitle = __('Add to Cart'); ?>
 
 <?php if ($_product->isSaleable()): ?>
 <div class="box-tocart">
     <div class="fieldset">
         <?php if ($block->shouldRenderQuantity()): ?>
         <div class="field qty">
             <label class="label" for="qty"><span><?php echo __('Qty') ?></span></label>
 
             <!-- Knockout JS Integration -->
             <script type="text/x-magento-init">
             {
                 "*": {
                     "Magento_Ui/js/core/app": {
                         "components": {
                             "qty_change": {
                                 "component": "Mageplaza_HelloWorld/js/view/product/view/qty_change",
                                 "defaultQty": <?php echo $block->getProductDefaultQty() * 1; ?>
                             }
                         }
                     }
                 }
             }
             </script>
 
             <div class="control" data-bind="scope: 'qty_change'">
                 <button data-bind="click: decreaseQty">-</button>
                 <input data-bind="value: qty()" 
                     type="number" 
                     name="qty" 
                     id="qty"
                     maxlength="12" 
                     title="<?php echo __('Qty') ?>" 
                     class="input-text qty"
                     data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                 />
                 <button data-bind="click: increaseQty">+</button>
             </div>
         </div>
         <?php endif; ?>
 
         <div class="actions">
             <button type="submit" 
                 title="<?php echo $buttonTitle ?>" 
                 class="action primary tocart" 
                 id="product-addtocart-button">
                 <span><?php echo $buttonTitle ?></span>
             </button>
             <?php echo $block->getChildHtml('', true) ?>
         </div>
     </div>
 </div>
 <?php endif; ?>